export { default as HomePage } from "./Homepage"
export { default as ContactsPage } from "./Contacts"
export { default as HomeLayoutPage } from "./HomeLayout"
export { default as AboutMePage } from "./AboutMe"
export { default as ProjectsPage } from "./Projects"
export { default as ErrorPage } from "./Error"